[package]
name = "rotero-pdf"
version.workspace = true
edition.workspace = true

[dependencies]
rotero-models.workspace = true
thiserror.workspace = true
serde.workspace = true
tracing.workspace = true
pdfrum = { git = "https://github.com/PoHsuanLai/pdfrum", rev = "5c1c889c6769b94e14aaf52f053537cbb90bfe72", features = ["png", "markdown"] }
base64 = "0.23"
serde_json = "1"

[dev-dependencies]
chrono.workspace = true
tempfile.workspace = true
