[package]
name = "rotero-pdf"
version.workspace = true
edition.workspace = true

[dependencies]
rotero-models.workspace = true
thiserror.workspace = true
serde.workspace = true
tracing.workspace = true
pdfrum = { git = "https://github.com/PoHsuanLai/pdfrum", rev = "f3bba7d843a111476251c9ecdd311071fdae50d0", features = ["png", "markdown"] }
base64 = "0.23"
serde_json = "1"

[dev-dependencies]
chrono.workspace = true
tempfile.workspace = true
